"""add quantity field to product table

Revision ID: 4781927a0c74
Revises: 7d517465a38e
Create Date: 2023-03-04 09:43:34.307116

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "4781927a0c74"
down_revision = "7d517465a38e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "quantity", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "quantity")
    # ### end Alembic commands ###
