"""add customer_id fk to products table

Revision ID: 67be0a1bc32c
Revises: 0ff05cd97743
Create Date: 2023-02-10 14:32:37.485522

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "67be0a1bc32c"
down_revision = "0ff05cd97743"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("customer_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_product_customer",
        "products",
        "customers",
        ["customer_id"],
        ["customer_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_product_customer", "products", type_="foreignkey")
    op.drop_column("products", "customer_id")
    # ### end Alembic commands ###
